name: CI/CD

on:
    push:
        branches:
            - master # 当 master 分支有代码更新时触发流水线

env:
    TZ: Asia/Shanghai

jobs:
    blog-cicd:
        name: build & deploy
        runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2

            - name: Setup node
              # 设置 node.js 环境
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'

            - name: Cache node modules
              # 设置包缓存目录，避免每次下载
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: |
                  npm install -g yarn
                  yarn
                  yarn build

            - name: Deploy
              env:
                  # Github 仓库地址（换成你自己的仓库地址）
                  GITHUB_REPO: github.com/l123wx/variant-form3-vite
              run: |
                  cd ./dist && git init && git add .
                  git config user.name "your name"
                  git config user.email "your email"
                  git add .
                  git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
                  git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:website